services:
    _defaults:
        autowire:      true
        autoconfigure: true
        bind:
            $bundleConfig: "%huh_backend_lost_password%"

    HeimrichHannot\BackendLostPasswordBundle\:
        resource: ../src/
        exclude:
            - ../src/{ContaoManager,DependencyInjection}
